import { Route } from '@/types/navigation'

export enum ToolVariant {
  GENERIC = 'generic',
  YOGA = 'yoga',
  WELLNESS = 'wellness',
  MEDITATION = 'meditation',
  COACHING = 'coaching',
}

export const TOOL_VARIANT_ROUTES: Record<ToolVariant, Route> = {
  [ToolVariant.GENERIC]: Route.RETREAT_PROFITABILITY_CALCULATOR,
  [ToolVariant.YOGA]: Route.YOGA_RETREAT_PRICING_CALCULATOR,
  [ToolVariant.WELLNESS]: Route.WELLNESS_RETREAT_PRICING_CALCULATOR,
  [ToolVariant.MEDITATION]: Route.MEDITATION_RETREAT_PRICING_CALCULATOR,
  [ToolVariant.COACHING]: Route.COACHING_RETREAT_PRICING_CALCULATOR,
}

export const CALCULATOR_INPUT_RANGES = {
  GUESTS_MIN: 4,
  GUESTS_MAX: 30,
  NIGHTS_MIN: 2,
  NIGHTS_MAX: 10,
  PRICE_PER_GUEST_MIN: 500,
  PRICE_PER_GUEST_MAX: 5000,
  VENUE_PER_NIGHT_MIN: 0,
  VENUE_PER_NIGHT_MAX: 100_000,
  FOOD_PER_GUEST_PER_DAY_MIN: 0,
  FOOD_PER_GUEST_PER_DAY_MAX: 500,
  FACILITATOR_FEE_MIN: 0,
  FACILITATOR_FEE_MAX: 1_000_000,
  MARKETING_AND_OTHER_MIN: 0,
  MARKETING_AND_OTHER_MAX: 1_000_000,
  TRAVEL_MIN: 0,
  TRAVEL_MAX: 1_000_000,
  INSURANCE_MIN: 0,
  INSURANCE_MAX: 100_000,
  PAYMENT_FEE_PERCENT_MIN: 0,
  PAYMENT_FEE_PERCENT_MAX: 20,
  PLANNING_DAYS_MIN: 0,
  PLANNING_DAYS_MAX: 365,
} as const

export const CALCULATOR_INPUT_DEFAULTS = {
  PAYMENT_FEE_PERCENT: 3,
} as const

export const CALCULATOR_URL_PARAMS = {
  GUESTS: 'g',
  NIGHTS: 'n',
  PRICE_PER_GUEST: 'p',
  VENUE: 'v',
  FOOD_PER_DAY: 'f',
  FACILITATOR_FEE: 'ff',
  MARKETING_OTHER: 'm',
  TRAVEL: 't',
  INSURANCE: 'i',
  PAYMENT_FEE_PERCENT: 'pf',
  PLANNING_DAYS: 'pd',
  HIRES_FACILITATORS: 'h',
} as const

export const MAKERSBARN_CTA_QUERY_PARAM = 'src' as const
export const MAKERSBARN_CTA_QUERY_VALUE_PREFIX = 'tool-' as const

export const CALCULATOR_RATE_LIMIT = {
  WINDOW_MS: 60_000,
  MAX_REQUESTS: 5,
} as const

export const SILO_TO_TOOL_ROUTE: Partial<Record<Route, Route>> = {
  [Route.YOGA_TEACHERS]: Route.YOGA_RETREAT_PRICING_CALCULATOR,
  [Route.WELLNESS_DETOX_RETREATS]: Route.WELLNESS_RETREAT_PRICING_CALCULATOR,
  [Route.MEDITATION_RETREATS]: Route.MEDITATION_RETREAT_PRICING_CALCULATOR,
  [Route.COACHING_INTENSIVES]: Route.COACHING_RETREAT_PRICING_CALCULATOR,
}
