import { Language } from '@/types/common'
import type { AuditUiLabels, LocalizedString } from '@/types/tools'

// Translation helper — emitted by scripts/apply_audit_translations.py.
const localized = (en: string, nl: string, de: string): LocalizedString => ({
  [Language.EN]: en,
  [Language.NL]: nl,
  [Language.DE]: de,
})

/**
 * Shared UI chrome for the audit. EN/NL/DE translations were generated by
 * language-specialised copywriter agents and applied via the
 * scripts/apply_audit_translations.py pipeline.
 */

export const AUDIT_LABELS: AuditUiLabels = {
  introEyebrow: localized('Before you start', 'Voor je begint', 'Bevor du startest'),
  introTitle: localized('What this audit checks, and what you get', 'Wat deze audit toetst, en wat je krijgt', 'Was dieses Audit prüft — und was du bekommst'),
  introBody: localized('Five minutes, 25 multiple-choice questions, and a personalised risk report. Nothing is sent or stored unless you ask us to email the report to you. The audit covers six categories — pricing, audience, venue, programme, legal, and group fit — and ranks the top mistakes worth fixing first.', 'Vijf minuten, 25 meerkeuzevragen en een persoonlijk risicorapport. Er wordt niets verzonden of opgeslagen, tenzij je ons vraagt het rapport naar je te mailen. De audit dekt zes categorieën — prijsstelling, publiek, locatie, programma, juridisch en groep-fit — en rangschikt de belangrijkste fouten om als eerste op te lossen.', 'Fünf Minuten, 25 Multiple-Choice-Fragen, ein persönlicher Risikoreport. Nichts wird verschickt oder gespeichert, solange du uns nicht bittest, dir den Report per E-Mail zu schicken. Das Audit deckt sechs Kategorien ab — Preis, Zielgruppe, Location, Programm, Recht und Gruppen-Fit — und reiht die Fehler nach Priorität.'),
  introBullets: [
    localized('25 questions across 6 mistake categories', '25 vragen verdeeld over 6 categorieën met veelgemaakte fouten', '25 Fragen über 6 Fehler-Kategorien'),
    localized('Per-category red / amber / green risk band', 'Per categorie een risico-indicatie: rood, oranje of groen', 'Pro Kategorie eine Risiko-Einstufung: rot, gelb oder grün'),
    localized('Top 5 mistakes ranked by impact, with a fix for each', 'Top 5 fouten gerangschikt op impact, met per fout een concrete oplossing', 'Top 5 Fehler nach Auswirkung sortiert, jeweils mit Lösungsansatz'),
    localized('Save and resume anytime — your answers stay in your browser', 'Tussentijds opslaan en hervatten kan altijd — je antwoorden blijven in je browser', 'Jederzeit speichern und fortsetzen — deine Antworten bleiben in deinem Browser'),
  ],
  introCta: localized('Start the audit', 'Start de audit', 'Audit starten'),
  reportHeading: localized('Your retreat risk report', 'Jouw retraite-risicorapport', 'Dein Retreat-Risikoreport'),
  resultLeadIn: localized('Here\'s where your plan sits across the six common-mistake categories. Below the cards are the specific items most worth fixing first, ranked by impact.', 'Hier zie je waar jouw plan staat in de zes categorieën met veelgemaakte fouten. Onder de kaarten staan de specifieke punten die het meest opleveren als je ze als eerste aanpakt, gerangschikt op impact.', 'Hier siehst du, wo dein Plan in den sechs Fehler-Kategorien steht. Unter den Karten findest du die konkreten Punkte, die nach Auswirkung sortiert zuerst behoben werden sollten.'),
  resultVerdictTemplate: localized('{red} red · {amber} amber · {green} green across 6 categories', '{red} rood · {amber} oranje · {green} groen verdeeld over 6 categorieën', '{red} rot · {amber} gelb · {green} grün über 6 Kategorien'),
  resultBandLabels: {
    green: localized('Low risk', 'Laag risico', 'Geringes Risiko'),
    amber: localized('Watch this', 'Let hierop', 'Im Auge behalten'),
    red: localized('High risk', 'Hoog risico', 'Hohes Risiko'),
  },
  fixesHeading: localized('Top mistakes to fix first', 'Belangrijkste fouten om eerst aan te pakken', 'Diese Fehler zuerst beheben'),
  nextLabel: localized('Next', 'Volgende', 'Weiter'),
  backLabel: localized('Back', 'Terug', 'Zurück'),
  restartLabel: localized('Restart audit', 'Audit opnieuw starten', 'Audit neu starten'),
  progressLabel: localized('Question {current} of {total} · {category}', 'Vraag {current} van {total} · {category}', 'Frage {current} von {total} · {category}'),
  howToHeading: localized('How the audit works', 'Hoe deze audit werkt', 'So funktioniert das Audit'),
  howToSteps: [
    localized('Answer 25 multiple-choice questions about your retreat plan — pricing, audience, venue, programme, legal, fit.', 'Beantwoord 25 meerkeuzevragen over je retraiteplan — prijsstelling, publiek, locatie, programma, juridisch en doelgroep-fit.', 'Beantworte 25 Multiple-Choice-Fragen zu deinem Retreat-Plan — Preis, Zielgruppe, Location, Programm, Recht, Fit.'),
    localized('Each answer scores risk against the most-cited mistakes in retreat-industry sources. Eight high-impact questions carry a 2× weighting.', 'Elk antwoord scoort risico aan de hand van de meest genoemde fouten in bronnen uit de retraite-industrie. Acht vragen met hoge impact tellen dubbel.', 'Jede Antwort wird gegen die meistgenannten Fehler aus Quellen der Retreat-Branche bewertet. Acht Fragen mit hoher Auswirkung zählen doppelt.'),
    localized('You get a per-category risk band (low / watch / high) and the top 5 mistakes to fix first.', 'Je krijgt per categorie een risico-indicatie (laag / let op / hoog) en de top 5 fouten om als eerste aan te pakken.', 'Du erhältst pro Kategorie eine Risiko-Einstufung (gering / Achtung / hoch) und die Top 5 Fehler, die du zuerst angehen solltest.'),
    localized('Nothing is saved server-side until you ask. Run the audit again as your plan firms up.', 'Er wordt niets server-side opgeslagen tenzij je daar zelf om vraagt. Doe de audit gerust opnieuw als je plan vorm krijgt.', 'Bis du es ausdrücklich willst, wird nichts auf dem Server gespeichert. Wiederhole das Audit, sobald dein Plan konkreter wird.'),
  ],
  faqHeading: localized('Frequently asked', 'Veelgestelde vragen', 'Häufig gefragt'),
  relatedHeading: localized('Related tools', 'Gerelateerde tools', 'Verwandte Tools'),
  hostARetreatTitle: localized('Host a retreat at The Makers Barn', 'Organiseer een retraite bij The Makers Barn', 'Retreat im The Makers Barn veranstalten'),
  pricingCalculatorTitle: localized('Run the pricing calculator', 'Open de prijscalculator', 'Den Preisrechner nutzen'),
  calendarTitle: localized('See the 6-month launch calendar', 'Bekijk de lanceringskalender van 6 maanden', 'Den 6-Monats-Launchkalender ansehen'),
  previewHeading: localized('A preview of the most-flagged mistakes', 'Een voorproefje van de meest voorkomende fouten', 'Eine Vorschau auf die häufigsten Fehler'),
  previewIntro: localized('Not ready to take the audit yet? Here\'s a quick read of the mistakes that show up most often when retreat hosts look back at editions that didn\'t work.', 'Nog niet klaar voor de audit? Hieronder een korte blik op de fouten die het vaakst terugkomen wanneer retraite-hosts terugkijken op edities die niet liepen.', 'Noch nicht bereit für das Audit? Hier ein kurzer Überblick über die Fehler, die am häufigsten auftauchen, wenn Retreat-Hosts auf Editionen zurückblicken, die nicht funktioniert haben.'),
  sourcesHeading: localized('Where the audit content comes from', 'Waar de inhoud van deze audit op gebaseerd is', 'Woher die Audit-Inhalte stammen'),
  sourcesIntro: localized('The audit reflects guidance that recurs across at least three independent retreat-industry sources. The full list:', 'De audit weerspiegelt inzichten die in minstens drie onafhankelijke bronnen uit de retraite-industrie terugkomen. De volledige lijst:', 'Das Audit spiegelt Empfehlungen wider, die in mindestens drei unabhängigen Quellen der Retreat-Branche wiederkehren. Die vollständige Liste:'),
  authorshipEyebrow: localized('About this audit', 'Over deze audit', 'Über dieses Audit'),
  authorshipTitle: localized('Built by retreat hosts who see these mistakes happen', 'Gemaakt door retraite-hosts die deze fouten in de praktijk zien gebeuren', 'Entwickelt von Retreat-Hosts, die diese Fehler immer wieder erleben'),
  authorshipBody: localized('We run The Makers Barn — a slow-living retreat venue in the Dutch countryside — and see the same handful of organiser mistakes repeat across every season. The audit is what we wish first-time hosts had run before they signed a venue contract or opened ticket sales. It is free to use, and there is no signup.', 'Wij runnen The Makers Barn — een slow-living retraitelocatie op het Nederlandse platteland — en zien elk seizoen dezelfde handvol organisator-fouten terugkomen. Deze audit is wat we beginnende hosts hadden willen meegeven vóórdat ze een locatiecontract tekenden of de ticketverkoop openden. Hij is gratis te gebruiken en je hoeft je niet aan te melden.', 'Wir betreiben The Makers Barn — eine Slow-Living-Retreat-Location auf dem niederländischen Land — und sehen Saison für Saison dieselbe Handvoll Veranstalter-Fehler. Das Audit ist das, was wir uns für Erstveranstalter wünschen, bevor sie einen Location-Vertrag unterschreiben oder den Ticketverkauf öffnen. Die Nutzung ist kostenlos, eine Anmeldung ist nicht nötig.'),
  authorshipCta: localized('Visit The Makers Barn →', 'Bezoek The Makers Barn →', 'The Makers Barn besuchen →'),
  crossLinksHeading: localized('Run the audit for a different niche', 'Doe de audit voor een andere niche', 'Das Audit für eine andere Nische ausführen'),
  crossLinksIntro: localized('Each variant tunes the questions and the long-form content to the niche. Pick the one closest to your retreat:', 'Elke variant stemt de vragen en de uitgebreide content af op de niche. Kies de versie die het dichtst bij jouw retraite ligt:', 'Jede Variante stimmt die Fragen und die ausführlichen Inhalte auf die Nische ab. Wähle die, die deinem Retreat am nächsten kommt:'),
}
