import { AuditVariant } from '@/constants/tools'
import { Language } from '@/types/common'
import type {
  AuditFaqEntry,
  AuditVariantConfig,
  LocalizedString,
} from '@/types/tools'

/**
 * Audit variants. EN/NL/DE translations were generated by language-specialised
 * copywriter agents and applied via scripts/apply_audit_translations.py.
 */
const localized = (en: string, nl: string, de: string): LocalizedString => ({
  [Language.EN]: en,
  [Language.NL]: nl,
  [Language.DE]: de,
})

const SHARED_FAQ: readonly AuditFaqEntry[] = [
  {
    question: localized('How long does the audit take?', 'Hoe lang duurt de audit?', 'Wie lange dauert das Audit?'),
    answer: localized('Most hosts finish in 5–7 minutes. There are 25 questions across six categories, all multiple choice.', 'De meeste hosts ronden hem af in 5–7 minuten. Het zijn 25 vragen verdeeld over zes categorieën, allemaal meerkeuze.', 'Die meisten Hosts sind in 5–7 Minuten durch. Es sind 25 Fragen über sechs Kategorien, alle Multiple Choice.'),
  },
  {
    question: localized('Is this a calculator or a content quiz?', 'Is dit een calculator of een contentquiz?', 'Ist das ein Rechner oder ein Inhalts-Quiz?'),
    answer: localized('It\'s a self-assessment, not a calculator. Each answer scores risk against the most common mistakes documented across retreat-industry sources, and the report shows your top mistakes to fix first.', 'Het is een zelfevaluatie, geen rekenmachine. Elk antwoord scoort risico op de meest gedocumenteerde fouten in de retraite-industrie, en het rapport laat zien welke fouten je als eerste moet aanpakken.', 'Es ist eine Selbsteinschätzung, kein Kalkulator. Jede Antwort bewertet das Risiko anhand der häufigsten Fehler, die in Quellen aus der Retreat-Branche dokumentiert sind. Der Bericht zeigt dir, welche Fehler du zuerst beheben solltest.'),
  },
  {
    question: localized('Do you save my answers?', 'Bewaren jullie mijn antwoorden?', 'Speichert ihr meine Antworten?'),
    answer: localized('Nothing is sent or stored unless you ask us to email the report to you. Until then it lives only in your browser.', 'Er wordt niets verzonden of opgeslagen, tenzij je ons vraagt het rapport naar je te mailen. Tot die tijd staat het alleen in je browser.', 'Bis du uns ausdrücklich bittest, dir den Report per E-Mail zu schicken, wird nichts verschickt oder gespeichert. Bis dahin lebt alles nur in deinem Browser.'),
  },
  {
    question: localized('Where do the mistakes come from?', 'Waar komen de fouten vandaan?', 'Woher stammen die Fehler?'),
    answer: localized('A meta-review of guidance from WeTravel, SquadTrip, Wanderlust Entrepreneur, Retreat & Grow Rich, Insight Timer, and a dozen other practitioner sources. The mistakes that recurred across at least three sources made it into the audit.', 'Een meta-analyse van inzichten van WeTravel, SquadTrip, Wanderlust Entrepreneur, Retreat & Grow Rich, Insight Timer en een tiental andere bronnen uit de praktijk. De fouten die in minstens drie bronnen terugkwamen, hebben de audit gehaald.', 'Aus einer Meta-Auswertung von Empfehlungen aus WeTravel, SquadTrip, Wanderlust Entrepreneur, Retreat & Grow Rich, Insight Timer und einem Dutzend weiterer Praktiker-Quellen. Fehler, die in mindestens drei Quellen wiederkehrten, haben es ins Audit geschafft.'),
  },
] as const

const SHARED_EYEBROW: LocalizedString = localized('Free readiness check', 'Gratis readiness-check', 'Kostenloser Readiness-Check')

const GENERIC: AuditVariantConfig = {
  variant: AuditVariant.GENERIC,
  faq: SHARED_FAQ,
  relatedVariants: [
    AuditVariant.FIRST_TIME,
    AuditVariant.YOGA,
    AuditVariant.WELLNESS,
  ],
  copy: {
    heroEyebrow: SHARED_EYEBROW,
    heroTitle: localized('The Retreat Mistakes Audit', 'De Retreat Mistakes Audit', 'Das Retreat Mistakes Audit'),
    heroIntro: localized('Before you sign a venue or open ticket sales, run the 25 most common retreat-host mistakes against your plan. The audit takes five minutes, scores risk across six categories — pricing, audience, venue, programme, legal, group fit — and gives you a personalised report ranking the mistakes most worth fixing first. Nothing is sent or stored unless you ask. Built from a meta-review of two dozen retreat-industry sources.', 'Voordat je een locatie tekent of de ticketverkoop opent, leg je de 25 meest voorkomende fouten van retraite-organisatoren naast je plan. De audit duurt vijf minuten, scoort risico in zes categorieën — prijsstelling, publiek, locatie, programma, juridisch, doelgroep-fit — en geeft je een persoonlijk rapport met de fouten die het eerst aandacht verdienen. Er wordt niets verzonden of opgeslagen, tenzij je daarom vraagt. Gebaseerd op een meta-review van twee dozijn bronnen uit de retraite-industrie.', 'Bevor du eine Location unterschreibst oder den Ticketverkauf öffnest, prüfe die 25 häufigsten Fehler von Retreat-Hosts gegen deinen Plan. Der Audit dauert fünf Minuten, bewertet das Risiko in sechs Kategorien — Preis, Zielgruppe, Location, Programm, Recht, Gruppen-Fit — und liefert dir einen persönlichen Bericht, der die Fehler nach Priorität ordnet. Es wird nichts gesendet oder gespeichert, außer du fragst aktiv danach. Basiert auf einer Meta-Auswertung von zwei Dutzend Quellen aus der Retreat-Branche.'),
    metaTitle: localized('Retreat Mistakes Audit — Free 25-question readiness check', 'Retreat Mistakes Audit — gratis readiness-check met 25 vragen', 'Retreat Mistakes Audit — Kostenloser Readiness-Check mit 25 Fragen'),
    metaDescription: localized('A free 5-minute audit of the 25 most common retreat-host mistakes — pricing, marketing, venue, programme, legal, and audience fit. Get a personalised risk report.', 'Een gratis audit van 5 minuten over de 25 meest voorkomende fouten van retraite-hosts — prijsstelling, marketing, locatie, programma, juridisch en doelgroep-fit. Inclusief een persoonlijk risicorapport.', 'Ein kostenloses 5-Minuten-Audit der 25 häufigsten Fehler von Retreat-Hosts — Preis, Marketing, Location, Programm, Recht und Zielgruppen-Fit. Du erhältst einen persönlichen Risikoreport.'),
  },
}

const FIRST_TIME: AuditVariantConfig = {
  variant: AuditVariant.FIRST_TIME,
  faq: SHARED_FAQ,
  relatedVariants: [
    AuditVariant.GENERIC,
    AuditVariant.YOGA,
    AuditVariant.WELLNESS,
  ],
  hideQuestionIds: ['f3-power-mix'],
  copy: {
    heroEyebrow: SHARED_EYEBROW,
    heroTitle: localized('First-Time Retreat Host Audit', 'Audit voor first-time retraite-hosts', 'Audit für Erstveranstalter von Retreats'),
    heroIntro: localized('Hosting your first retreat is largely a question of which mistakes you walk into. The same handful — pricing for sell-out, building before the list exists, booking a venue you have not stayed at, relying on the venue\'s insurance — show up across every retreat post-mortem. This 5-minute audit runs the 25 most common first-time mistakes past your plan and ranks the ones most worth fixing first. No signup, nothing saved server-side.', 'Je eerste retraite organiseren komt grotendeels neer op de vraag in welke fouten je trapt. Steeds dezelfde handvol — prijzen op uitverkoop, bouwen voordat de lijst er is, een locatie boeken waar je nooit hebt overnacht, leunen op de verzekering van de locatie — duikt op in elke retraite-evaluatie. Deze audit van vijf minuten legt de 25 meest gemaakte beginnersfouten naast je plan en rangschikt welke je het eerst zou moeten oplossen. Geen aanmelding, niets wordt server-side opgeslagen.', 'Dein erstes Retreat zu veranstalten ist vor allem die Frage, in welche Fehler du läufst. Dieselbe Handvoll — auf Ausverkauf kalkulieren, bauen bevor die Liste existiert, eine Location buchen, in der du nie übernachtet hast, dich auf die Versicherung der Location verlassen — taucht in jedem Retreat-Post-mortem auf. Dieser 5-Minuten-Audit prüft die 25 häufigsten Anfänger-Fehler gegen deinen Plan und ordnet die nach Priorität, die du zuerst beheben solltest. Keine Anmeldung, nichts wird serverseitig gespeichert.'),
    metaTitle: localized('First-Time Retreat Host Audit — Avoid the 25 Most Common Mistakes', 'Audit voor first-time retraite-hosts — voorkom de 25 meest voorkomende fouten', 'Audit für Erstveranstalter von Retreats — Vermeide die 25 häufigsten Fehler'),
    metaDescription: localized('Hosting your first retreat? Take this free 5-minute audit of the 25 most common first-time mistakes and get a personalised risk report.', 'Organiseer je je eerste retraite? Doe deze gratis audit van vijf minuten over de 25 meest gemaakte beginnersfouten en ontvang een persoonlijk risicorapport.', 'Planst du dein erstes Retreat? Mach diesen kostenlosen 5-Minuten-Audit zu den 25 häufigsten Anfänger-Fehlern und erhalte einen persönlichen Risikobericht.'),
  },
}

const YOGA: AuditVariantConfig = {
  variant: AuditVariant.YOGA,
  faq: SHARED_FAQ,
  relatedVariants: [
    AuditVariant.WELLNESS,
    AuditVariant.MEDITATION,
    AuditVariant.GENERIC,
  ],
  copy: {
    heroEyebrow: SHARED_EYEBROW,
    heroTitle: localized('Yoga Retreat Mistakes Audit', 'Audit Yogaretraite-fouten', 'Yoga-Retreat-Fehler-Audit'),
    heroIntro: localized('Yoga retreats live or die on three things: the warm list you bring, the price you set, and the venue contract you signed. Get any one of those wrong and the retreat either does not fill or does not pay. This 5-minute audit runs the 25 most common yoga-retreat mistakes past your plan — pricing tier, marketing runway, insurance gaps, programme density — and ranks the ones most worth fixing first.', 'Yogaretraites staan of vallen met drie dingen: het warme netwerk dat je meebrengt, de prijs die je vraagt, en het locatiecontract dat je hebt getekend. Eén daarvan verkeerd en de retraite vult niet of dekt de kosten niet. Deze audit van vijf minuten legt de 25 meest gemaakte fouten bij yogaretraites naast je plan — prijssegment, marketingaanloop, hiaten in de verzekering, programmadichtheid — en rangschikt welke het eerst aandacht verdienen.', 'Yoga-Retreats stehen und fallen mit drei Dingen: der warmen Liste, die du mitbringst, dem Preis, den du ansetzt, und dem Vertrag mit der Location. Verfehlst du eines davon, füllt sich das Retreat nicht oder es trägt sich nicht. Dieser 5-Minuten-Audit prüft die 25 häufigsten Fehler bei Yoga-Retreats gegen deinen Plan — Preisniveau, Marketing-Vorlauf, Versicherungslücken, Programmdichte — und ordnet die nach Priorität, die du zuerst beheben solltest.'),
    metaTitle: localized('Yoga Retreat Mistakes Audit — Free 5-Minute Readiness Check', 'Audit Yogaretraite-fouten — Gratis readiness check van 5 minuten', 'Yoga-Retreat-Fehler-Audit — kostenloser 5-Minuten-Readiness-Check'),
    metaDescription: localized('Free audit of the 25 most common yoga retreat mistakes — pricing, marketing, venue, programme, liability, group fit. Get a personalised risk report.', 'Gratis audit van de 25 meest gemaakte fouten bij yogaretraites — prijsstelling, marketing, locatie, programma, aansprakelijkheid, doelgroep-fit. Ontvang een persoonlijk risicorapport.', 'Kostenloser Audit der 25 häufigsten Fehler bei Yoga-Retreats — Preis, Marketing, Location, Programm, Haftung, Gruppen-Fit. Mit persönlichem Risikobericht.'),
  },
}

const WELLNESS: AuditVariantConfig = {
  variant: AuditVariant.WELLNESS,
  faq: SHARED_FAQ,
  relatedVariants: [
    AuditVariant.YOGA,
    AuditVariant.MEDITATION,
    AuditVariant.GENERIC,
  ],
  copy: {
    heroEyebrow: SHARED_EYEBROW,
    heroTitle: localized('Wellness Retreat Mistakes Audit', 'Audit Wellnessretraite-fouten', 'Wellness-Retreat-Fehler-Audit'),
    heroIntro: localized('Wellness retreats run longer and cost more, which means each common mistake costs more too. A flat cancellation policy, an under-buffered budget, an insurance line that does not cover guest practitioners — any of these can absorb the entire margin on a 7-day programme. This 5-minute audit runs the 25 most common wellness-retreat mistakes past your plan and ranks the ones most worth fixing first.', 'Wellnessretraites duren langer en kosten meer, dus elke veelgemaakte fout kost ook meer. Een uniform annuleringsbeleid, een budget zonder buffer, een verzekeringsregel die externe behandelaars niet dekt — elk daarvan kan de hele marge op een 7-daags programma opslokken. Deze audit van vijf minuten legt de 25 meest gemaakte fouten bij wellnessretraites naast je plan en rangschikt welke het eerst aandacht verdienen.', 'Wellness-Retreats laufen länger und kosten mehr, was bedeutet, dass jeder typische Fehler auch teurer wird. Eine pauschale Stornoregel, ein Budget ohne Puffer, eine Versicherungspolice, die mitwirkende Praktizierende nicht abdeckt — jedes davon kann die gesamte Marge eines 7-Tage-Programms aufzehren. Dieser 5-Minuten-Audit prüft die 25 häufigsten Fehler bei Wellness-Retreats gegen deinen Plan und ordnet die nach Priorität, die du zuerst beheben solltest.'),
    metaTitle: localized('Wellness Retreat Mistakes Audit — Free 5-Minute Readiness Check', 'Audit Wellnessretraite-fouten — Gratis readiness check van 5 minuten', 'Wellness-Retreat-Fehler-Audit — kostenloser 5-Minuten-Readiness-Check'),
    metaDescription: localized('Free audit of the 25 most common wellness/detox retreat mistakes — pricing, marketing, venue, programme, legal, fit. Get a personalised risk report.', 'Gratis audit van de 25 meest gemaakte fouten bij wellness- en detoxretraites — prijsstelling, marketing, locatie, programma, juridisch, doelgroep-fit. Ontvang een persoonlijk risicorapport.', 'Kostenloser Audit der 25 häufigsten Fehler bei Wellness- und Detox-Retreats — Preis, Marketing, Location, Programm, Recht, Fit. Mit persönlichem Risikobericht.'),
  },
}

const MEDITATION: AuditVariantConfig = {
  variant: AuditVariant.MEDITATION,
  faq: SHARED_FAQ,
  relatedVariants: [
    AuditVariant.YOGA,
    AuditVariant.WELLNESS,
    AuditVariant.GENERIC,
  ],
  copy: {
    heroEyebrow: SHARED_EYEBROW,
    heroTitle: localized('Meditation Retreat Mistakes Audit', 'Audit Meditatieretraite-fouten', 'Meditations-Retreat-Fehler-Audit'),
    heroIntro: localized('Meditation retreats fail on a different pattern from yoga or wellness — over-promising silent transformation, skipping participant screening, getting blindsided by a dharma centre\'s cancellation policy. This 5-minute audit runs the 25 most common meditation-retreat mistakes past your plan and ranks the ones most worth fixing first. Particular focus on participant screening and contemplative-format risk.', 'Meditatieretraites lopen op een ander patroon stuk dan yoga of wellness — te veel beloven over stille transformatie, deelnemers niet screenen, verrast worden door het annuleringsbeleid van een dharmacentrum. Deze audit van vijf minuten legt de 25 meest gemaakte fouten bij meditatieretraites naast je plan en rangschikt welke het eerst aandacht verdienen. Met bijzondere focus op deelnemerscreening en risico\'s van het contemplatieve format.', 'Meditations-Retreats scheitern an einem anderen Muster als Yoga oder Wellness — übertriebene Versprechen stiller Transformation, fehlendes Teilnehmer-Screening, böse Überraschungen mit den Stornoregeln eines Dharma-Zentrums. Dieser 5-Minuten-Audit prüft die 25 häufigsten Fehler bei Meditations-Retreats gegen deinen Plan und ordnet die nach Priorität, die du zuerst beheben solltest. Mit besonderem Fokus auf Teilnehmer-Screening und das Risiko kontemplativer Formate.'),
    metaTitle: localized('Meditation Retreat Mistakes Audit — Free 5-Minute Readiness Check', 'Audit Meditatieretraite-fouten — Gratis readiness check van 5 minuten', 'Meditations-Retreat-Fehler-Audit — kostenloser 5-Minuten-Readiness-Check'),
    metaDescription: localized('Free audit of the 25 most common meditation retreat mistakes — pricing, marketing, venue, programme, screening, legal. Get a personalised risk report.', 'Gratis audit van de 25 meest gemaakte fouten bij meditatieretraites — prijsstelling, marketing, locatie, programma, screening, juridisch. Ontvang een persoonlijk risicorapport.', 'Kostenloser Audit der 25 häufigsten Fehler bei Meditations-Retreats — Preis, Marketing, Location, Programm, Screening, Recht. Mit persönlichem Risikobericht.'),
  },
}

const COACHING: AuditVariantConfig = {
  variant: AuditVariant.COACHING,
  faq: SHARED_FAQ,
  relatedVariants: [
    AuditVariant.WELLNESS,
    AuditVariant.MEDITATION,
    AuditVariant.GENERIC,
  ],
  copy: {
    heroEyebrow: SHARED_EYEBROW,
    heroTitle: localized('Coaching Retreat Mistakes Audit', 'Audit Coachingretraite-fouten', 'Coaching-Retreat-Fehler-Audit'),
    heroIntro: localized('Coaching intensives are smaller, higher-ticket, and unforgiving on group composition. Losing one guest from a six-person retreat is a 17% revenue hit; mixing power dynamics in the same room kills the vulnerability the retreat is selling. This 5-minute audit runs the 25 most common coaching-retreat mistakes past your plan — pricing, audience, group composition, legal — and ranks the ones most worth fixing first.', 'Coaching-intensives zijn kleiner, hoger geprijsd en onverbiddelijk wat groepssamenstelling betreft. Eén deelnemer kwijtraken op een retraite van zes is een omzetverlies van 17%; machtsverhoudingen mengen in dezelfde ruimte vernietigt de kwetsbaarheid die de retraite verkoopt. Deze audit van vijf minuten legt de 25 meest gemaakte fouten bij coachingretraites naast je plan — prijsstelling, publiek, groepssamenstelling, juridisch — en rangschikt welke het eerst aandacht verdienen.', 'Coaching-Intensivs sind kleiner, hochpreisiger und unverzeihlich, was die Gruppenzusammensetzung angeht. Einen Gast aus einem Sechs-Personen-Retreat zu verlieren bedeutet 17 % Umsatzverlust; Machtgefälle im selben Raum zu mischen tötet die Verletzlichkeit, die das Retreat verkauft. Dieser 5-Minuten-Audit prüft die 25 häufigsten Fehler bei Coaching-Retreats gegen deinen Plan — Preis, Zielgruppe, Gruppenzusammensetzung, Recht — und ordnet die nach Priorität, die du zuerst beheben solltest.'),
    metaTitle: localized('Coaching Retreat Mistakes Audit — Free 5-Minute Readiness Check', 'Audit Coachingretraite-fouten — Gratis readiness check van 5 minuten', 'Coaching-Retreat-Fehler-Audit — kostenloser 5-Minuten-Readiness-Check'),
    metaDescription: localized('Free audit of the 25 most common coaching retreat mistakes — pricing, audience, programme density, group fit, legal. Get a personalised risk report.', 'Gratis audit van de 25 meest gemaakte fouten bij coachingretraites — prijsstelling, publiek, programmadichtheid, doelgroep-fit, juridisch. Ontvang een persoonlijk risicorapport.', 'Kostenloser Audit der 25 häufigsten Fehler bei Coaching-Retreats — Preis, Zielgruppe, Programmdichte, Gruppen-Fit, Recht. Mit persönlichem Risikobericht.'),
  },
}

export const AUDIT_VARIANTS: Record<AuditVariant, AuditVariantConfig> = {
  [AuditVariant.GENERIC]: GENERIC,
  [AuditVariant.FIRST_TIME]: FIRST_TIME,
  [AuditVariant.YOGA]: YOGA,
  [AuditVariant.WELLNESS]: WELLNESS,
  [AuditVariant.MEDITATION]: MEDITATION,
  [AuditVariant.COACHING]: COACHING,
}
